-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 12, 2026 at 06:00 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `recipe_hub`
--

-- --------------------------------------------------------

--
-- Table structure for table `messages`
--

CREATE TABLE `messages` (
  `id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL UNIQUE,
  `message` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `messages`
--

INSERT INTO `messages` (`id`, `name`, `email`, `message`, `created_at`) VALUES
(1, 'dinundu', 'dinu@gmail.com', 'test 1', '2026-08-06 17:25:31'),
(2, 'yovindu', 'yovi@gmail.com', 'test2', '2026-08-06 17:26:13'),
(3, 'vihanga', 'vi@gmail.com', 'test3', '2026-08-06 17:29:35'),
(4, 'vihanga', 'vi@gmail.com', 'test3', '2026-08-06 17:36:54'),
(5, 'jejejeje', 'je@gmail.com', 'eedefrfevevv', '2026-08-12 06:19:26');

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `recipe_key` varchar(100) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `ingredients` text NOT NULL,
  `instructions` text NOT NULL,
  `prep_time` varchar(50) DEFAULT NULL,
  `cook_time` varchar(50) DEFAULT NULL,
  `total_time` varchar(50) DEFAULT NULL,
  `servings` varchar(50) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `recipe_key`, `title`, `description`, `image`, `ingredients`, `instructions`, `prep_time`, `cook_time`, `total_time`, `servings`, `user_id`) VALUES
(1, 'kottu', 'Sri Lankan Chicken Kottu', 'Sri Lankan Chicken Kottu is one of the country\'s most popular street foods. It is prepared by chopping soft Godamba roti into small pieces and stir-frying it with juicy chicken, fresh vegetables, eggs, aromatic spices, and flavorful sauces. The famous rhythmic chopping sound made while preparing Kottu has become a symbol of Sri Lankan street food culture.', 'Images/Recipes/Koththu.webp', 'Godamba roti, chicken, onion, leeks, cabbage, carrot, eggs, curry powder, chilli, salt and pepper.', '\r\n        Cut the Godamba roti into thin strips or small bite-sized pieces.,\r\n\r\n        Heat oil in a large pan or flat griddle and sauté garlic, ginger, onions, curry leaves, and green chilies until fragrant.,\r\n\r\n        Add the chicken pieces and cook until they are golden brown and fully cooked.,\r\n\r\n        Mix in the carrots, cabbage, and leeks, then stir-fry for about 3–4 minutes.,\r\n\r\n        Push the vegetables to one side of the pan, crack the eggs, scramble them, and combine with the vegetables.,\r\n\r\n        Add the chopped Godamba roti and mix thoroughly.,\r\n\r\n        Season with curry powder, chili powder, black pepper, soy sauce, tomato sauce, and salt.,\r\n\r\n        Continue tossing and chopping the mixture until everything is evenly coated and heated through.,\r\n\r\n        Serve hot with spicy chicken curry, chili paste, or a refreshing soft drink.', '20 min', '25 min', '45 min', '4 Servings', NULL),
(2, 'stringhoppers', 'Sri Lankan String Hoppers', 'Sri Lankan String Hoppers are a traditional steamed food made from rice flour dough pressed into thin noodle-like strands. They are soft, light, and commonly enjoyed as a breakfast or dinner meal in Sri Lankan households. String hoppers are usually served with coconut sambol, dhal curry, or different types of spicy curries, making them a popular and healthy traditional dish.', 'Images/Recipes/String_hoppers.jpg', 'Rice flour,\r\nWarm water,\r\nSalt,\r\nCoconut sambol,\r\nCoconut milk\r\n\r\n', 'Mix rice flour with warm water and salt to prepare a soft dough.\r\n\r\nKnead the dough until it becomes smooth and easy to press.\r\n\r\nPlace the dough into a string hopper press and create thin noodle strands.\r\n\r\nArrange the strands on circular mats or plates.\r\n\r\nSteam the string hoppers until they are fully cooked.\r\n\r\nServe hot with dhal curry, coconut sambol, or other Sri Lankan curries.\r\n', '30 min', '20 min', '50 min', '4 Servings', NULL),
(3, 'hoppers', 'Sri Lankan Hoppers', 'Sri Lankan Hoppers are a traditional bowl-shaped pancake made with fermented rice flour batter and coconut milk. They are crispy around the edges with a soft, fluffy center and are commonly enjoyed as a breakfast or dinner dish. Hoppers are usually served with coconut sambol, spicy curries, or a fried egg placed in the middle, making them one of the most loved foods in Sri Lankan cuisine.', 'Images/Recipes/Hoppers.jpg', 'Rice flour,\r\nCoconut milk,\r\nYeast,\r\nSugar,\r\nSalt,\r\nCoconut water', 'Prepare the hopper batter by mixing rice flour, coconut milk, yeast, sugar, and salt.\r\nAllow the batter to ferment for several hours to develop the flavour.\r\nHeat a hopper pan and pour a small amount of batter into it.\r\nSpread the batter around the pan to create a thin crispy edge.\r\nCook until the edges become golden and the center becomes soft.\r\nServe hot with coconut sambol, curry, or a fried egg.', '30 min', '20 min', '50 min', '10 Pieces', NULL),
(4, 'fish', 'Fish Ambul Thiyal', 'Fish Ambul Thiyal is a famous traditional Sri Lankan dry fish curry known for its unique sour and spicy flavour. This dish is prepared by cooking fish pieces with goraka, black pepper, and aromatic spices until the flavours are deeply absorbed. Originally popular in the southern coastal areas of Sri Lanka, Ambul Thiyal is usually served with steamed rice and is loved for its rich taste and long shelf life.', 'Images/Recipes/Malu.jpg', 'Fish pieces,\r\nGoraka,\r\nBlack pepper,\r\nGarlic,\r\nCinnamon,\r\nTurmeric powder,\r\nSalt,\r\nCurry leaves\r\n', 'Wash and clean the fish pieces properly.\r\n\r\nPrepare a spice mixture using goraka, black pepper, turmeric, garlic, and salt.\r\n\r\nCoat the fish pieces with the spice mixture and allow them to absorb the flavours.\r\n\r\nArrange the fish pieces in a clay pot and cook slowly with a small amount of water.\r\n\r\nSimmer until the fish becomes tender and the mixture turns into a thick dry curry.\r\n\r\nServe hot with steamed rice and traditional Sri Lankan side dishes.\r\n', '20 min', '30 min', '50 min', '4 Servings', NULL),
(5, 'dhal', 'Sri Lankan Dhal Curry', 'Sri Lankan Dhal Curry is a popular traditional dish made with red lentils, creamy coconut milk, and aromatic spices. It is a simple yet flavorful curry that is enjoyed in many Sri Lankan households. With its rich texture and mild spicy taste, dhal curry is commonly served with steamed rice, roti, string hoppers, or other traditional meals.', 'Images/Recipes/Dhal.jpg', 'Red lentils,\r\nCoconut milk,\r\nOnion,\r\nGarlic,\r\nGreen chilli,\r\nCurry leaves,\r\nTurmeric powder,\r\nSri Lankan spices,\r\nSalt\r\n', 'Wash the red lentils and cook them with water until they become soft.\r\nAdd turmeric powder, salt, and spices to the cooked lentils.\r\nPrepare the tempering by frying onion, garlic, green chilli, and curry leaves.\r\nMix the tempering with the cooked lentils to enhance the flavour.\r\nAdd coconut milk and simmer until the curry becomes creamy.\r\nServe hot with rice, roti, or string hoppers.', '10 min', '20 min', '30 min', '4 Servings', NULL),
(6, 'watalappan', 'Sri Lankan Watalappam', 'Sri Lankan Watalappam is a traditional steamed coconut custard pudding made with kithul treacle, coconut milk, eggs, and aromatic spices. It has a smooth, creamy texture and rich caramel-like flavour, making it a popular Sri Lankan dessert served during celebrations, festivals, and special occasions.', 'Images/Recipes/Watalappam.jpg', 'Eggs,\r\nKithul treacle,\r\nCoconut milk,\r\nCardamom,\r\nCashew nuts,\r\nNutmeg,\r\nVanilla essence,\r\nSalt', 'Crack the eggs into a mixing bowl and beat them gently.\r\n\r\nAdd kithul treacle and mix well until combined.\r\n\r\nAdd coconut milk, vanilla essence, crushed cardamom, nutmeg, and a small amount of salt.\r\n\r\nMix gently without creating too much foam.\r\n\r\nStrain the mixture to remove any unwanted egg particles.\r\n\r\nPour the mixture into a heatproof bowl or steaming dish.\r\n\r\nSprinkle chopped cashew nuts on top.\r\n\r\nSteam on medium heat until the custard is fully set.\r\n\r\nAllow the Watalappam to cool before serving.\r\n\r\nChill in the refrigerator for a few hours if desired.\r\n\r\nServe as a traditional Sri Lankan dessert.', '15 min', '45 min', '1 hour', '6 Servings', NULL),
(7, 'brinjalcurry', 'Sri Lankan Brinjal Curry', 'Sri Lankan Brinjal Curry is a flavourful traditional curry made with fried or roasted eggplant pieces cooked with coconut milk, onions, curry leaves, and a special blend of spices. The soft texture of brinjal combined with the rich and spicy gravy creates a unique taste loved by many Sri Lankan families. It is commonly served with rice and other side dishes as part of a traditional meal.', 'Images/Recipes/Brinjal_Curry.jpg', 'Brinjal,\r\nOnion,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCurry leaves,\r\nPandan leaves,\r\nCoconut milk,\r\nTurmeric powder,\r\nChili powder,\r\nCurry powder,\r\nRoasted curry powder,\r\nBlack pepper,\r\nCinnamon,\r\nSalt,\r\nCooking oil', 'Wash and cut the brinjal into medium-sized pieces.\r\n\r\nSprinkle the brinjal pieces with turmeric powder and salt.\r\n\r\nHeat oil in a pan and fry the brinjal pieces until lightly golden, then set them aside.\r\n\r\nIn the same pan, sauté onion, green chilies, garlic, ginger, curry leaves, and pandan leaves until fragrant.\r\n\r\nAdd chili powder, curry powder, roasted curry powder, black pepper, cinnamon, and salt and mix well.\r\n\r\nAdd the fried brinjal pieces and gently mix with the spices.\r\n\r\nPour in coconut milk and a small amount of water.\r\n\r\nCook on medium heat until the brinjal becomes tender and the curry thickens.\r\n\r\nSimmer for a few more minutes until the flavours combine well.\r\n\r\nServe hot with steamed rice, roti, string hoppers, or other traditional Sri Lankan side dishes.', '20 min', '30 min', '50 min', '4 Servings', NULL),
(8, 'potatocurry', 'Sri Lankan Potato Curry', 'Sri Lankan Potato Curry is a simple and delicious traditional curry made with tender potatoes, coconut milk, onions, curry leaves, and aromatic Sri Lankan spices. The creamy and mildly spicy gravy combines perfectly with the soft potatoes, making it a popular everyday dish commonly served with rice, roti, string hoppers, or other Sri Lankan meals.', 'Images/Recipes/Potato_Curry.jpg', 'Potatoes,\r\nOnion,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCurry leaves,\r\nPandan leaves,\r\nCoconut milk,\r\nTurmeric powder,\r\nChili powder,\r\nCurry powder,\r\nCinnamon,\r\nSalt,\r\nCooking oil', 'Wash, peel, and cut the potatoes into medium-sized pieces.\r\n\r\nHeat oil in a pan and sauté onion, green chilies, garlic, ginger, curry leaves, and pandan leaves until fragrant.\r\n\r\nAdd turmeric powder, chili powder, curry powder, cinnamon, and salt and mix well.\r\n\r\nAdd the potato pieces and mix them with the spices.\r\n\r\nPour in the coconut milk and the required amount of water.\r\n\r\nCook on medium heat until the potatoes become tender.\r\n\r\nSimmer for a few more minutes until the curry thickens and the flavours combine well.\r\n\r\nServe hot with steamed rice, roti, string hoppers, or other traditional Sri Lankan dishes.', '15 min', '30 min', '45 min', '4 Servings', NULL),
(9, 'pumpkincurry', 'Sri Lankan Pumpkin Curry', 'A traditional Sri Lankan pumpkin curry prepared with sweet pumpkin pieces, coconut milk, and mild spices. This creamy curry has a unique sweet and spicy flavour and is commonly enjoyed with rice and other traditional dishes.', 'Images/Recipes/Pumpkin_Curry.webp', 'Pumpkin,\r\nOnion,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCurry leaves,\r\nPandan leaves,\r\nCoconut milk,\r\nTurmeric powder,\r\nChili powder,\r\nCurry powder,\r\nRoasted curry powder,\r\nCinnamon,\r\nMustard seeds,\r\nSalt,\r\nCooking oil', 'Wash, peel, remove the seeds, and cut the pumpkin into medium-sized pieces.\r\n\r\nHeat oil in a pan and add mustard seeds.\r\n\r\nWhen the mustard seeds begin to splutter, add onion, green chilies, garlic, ginger, curry leaves, and pandan leaves and sauté until fragrant.\r\n\r\nAdd turmeric powder, chili powder, curry powder, roasted curry powder, cinnamon, and salt and mix well.\r\n\r\nAdd the pumpkin pieces and gently mix them with the spices.\r\n\r\nPour in the coconut milk and a small amount of water.\r\n\r\nCover the pan and cook on medium heat until the pumpkin becomes tender.\r\n\r\nSimmer for a few more minutes until the curry thickens and the flavours combine well.\r\n\r\nServe hot with steamed rice, roti, string hoppers, or other traditional Sri Lankan side dishes.', '15 min', '25 min', '40 min', '4 Servings', NULL),
(10, 'jackfruitcurry', 'Sri Lankan Jackfruit Curry', 'Sri Lankan Jackfruit Curry, also known as Polos Curry when made with young jackfruit, is a traditional dish cooked with coconut milk and a rich blend of spices. This flavorful curry has a meat-like texture and is a popular choice in Sri Lankan vegetarian cuisine.', 'Images/Recipes/Jackfruit_Curry.jpg', 'Young jackfruit,\r\nOnion,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCurry leaves,\r\nPandan leaves,\r\nCoconut milk,\r\nTurmeric powder,\r\nChili powder,\r\nCurry powder,\r\nRoasted curry powder,\r\nBlack pepper,\r\nCinnamon,\r\nCardamom,\r\nCloves,\r\nSalt,\r\nCooking oil', 'Wash and cut the young jackfruit into medium-sized pieces.\r\n\r\nHeat oil in a large pan and sauté onion, green chilies, garlic, ginger, curry leaves, and pandan leaves until fragrant.\r\n\r\nAdd turmeric powder, chili powder, curry powder, roasted curry powder, black pepper, cinnamon, cardamom, cloves, and salt and mix well.\r\n\r\nAdd the young jackfruit pieces and gently mix them with the spices.\r\n\r\nPour in coconut milk and the required amount of water.\r\n\r\nCover the pan and cook on medium heat until the jackfruit becomes tender and absorbs the spices.\r\n\r\nReduce the heat and simmer until the curry becomes thick and the flavours combine well.\r\n\r\nServe hot with steamed rice, roti, string hoppers, or other traditional Sri Lankan side dishes.', '20 min', '45 min', '1 hour 5 min', '5 Servings', NULL),
(11, 'vegetablebiriyani', 'Vegetable Biriyani', 'Vegetable Biriyani is a fragrant and flavourful rice dish prepared with basmati rice, mixed vegetables, aromatic spices, and fresh herbs. This colourful vegetarian dish is a delicious and filling meal commonly enjoyed with raita, curry, or other traditional side dishes.', 'Images/Recipes/Vegetable_Biriyani.jpg', 'Basmati rice,\r\nCarrot,\r\nBeans,\r\nGreen peas,\r\nPotato,\r\nOnion,\r\nGreen chilies,\r\nGinger and garlic,\r\nBiriyani spices,\r\nTurmeric powder,\r\nChili powder,\r\nCinnamon,\r\nCardamom,\r\nCloves,\r\nCoconut milk,\r\nSalt', 'Wash and soak the basmati rice for about 20 minutes.\r\n\r\nHeat oil or ghee in a large pot and sauté onions until golden brown.\r\n\r\nAdd ginger, garlic, green chilies, and the whole spices and sauté until fragrant.\r\n\r\nAdd carrots, beans, green peas, and potatoes and cook for a few minutes.\r\n\r\nAdd turmeric powder, chili powder, biriyani spices, and salt and mix well.\r\n\r\nAdd the soaked rice and gently mix with the vegetables and spices.\r\n\r\nPour in coconut milk and the required amount of water.\r\n\r\nCook on medium heat until the rice is almost done.\r\n\r\nReduce the heat, cover the pot, and cook until the rice becomes fluffy and the vegetables are tender.\r\n\r\nGently mix the biriyani and serve hot with raita, salad, or other Sri Lankan side dishes.', '30 min', '45 min', '1 hour 15 min', '4 Servings', NULL),
(12, 'chickenfriedrice', 'Sri Lankan Chicken Fried Rice', 'Sri Lankan Chicken Fried Rice is a delicious and flavourful rice dish prepared with cooked rice, tender chicken pieces, vegetables, eggs, and aromatic seasonings. The combination of fried rice, juicy chicken, and fresh vegetables makes it a popular meal enjoyed by families and commonly served with chilli paste, curry, or other side dishes.', 'Images/Recipes/Chicken_Fried_Rice.jpg', 'Cooked rice,\r\nChicken pieces,\r\nEggs,\r\nCarrot,\r\nLeeks,\r\nGreen peas,\r\nOnion,\r\nGarlic,\r\nGinger,\r\nGreen chilies,\r\nSoy sauce,\r\nPepper,\r\nChili sauce,\r\nSalt,\r\nCooking oil', 'Cut the chicken into small pieces and season with salt and pepper.\r\n\r\nHeat oil in a large pan or wok and stir-fry the chicken pieces until fully cooked.\r\n\r\nAdd chopped garlic, ginger, onion, and green chilies and sauté until fragrant.\r\n\r\nAdd carrots, green peas, and leeks and stir-fry for a few minutes.\r\n\r\nPush the ingredients to one side of the pan and scramble the eggs.\r\n\r\nAdd the cooked rice and mix well with the chicken and vegetables.\r\n\r\nAdd soy sauce, chili sauce, pepper, and salt according to taste.\r\n\r\nStir-fry everything on high heat until the rice becomes hot and the flavours combine well.\r\n\r\nAdd the remaining leeks and mix gently.\r\n\r\nServe hot with your favourite Sri Lankan side dishes.', '20 min', '25 min', '45 min', '4 Servings', NULL),
(13, 'paneerrice', 'Paneer Rice', 'Paneer Rice is a delicious and aromatic rice dish prepared with soft paneer cubes, basmati rice, vegetables, and a blend of Indian spices. The combination of fluffy rice and lightly fried paneer creates a satisfying vegetarian meal that can be enjoyed with raita, curry, or other side dishes.', 'Images/Recipes/Paneer_Rice.jpg', 'Basmati rice,\r\nPaneer cubes,\r\nCarrot,\r\nBeans,\r\nGreen peas,\r\nOnion,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCapsicum,\r\nSoy sauce,\r\nPepper,\r\nChili powder,\r\nTurmeric powder,\r\nSalt,\r\nCooking oil', 'Wash and soak the basmati rice for about 20 minutes.\r\n\r\nCut the paneer into small cubes.\r\n\r\nHeat oil in a pan and lightly fry the paneer cubes until golden brown, then set them aside.\r\n\r\nIn the same pan, sauté onion, garlic, ginger, and green chilies until fragrant.\r\n\r\nAdd carrots, beans, green peas, and capsicum and stir-fry for a few minutes.\r\n\r\nAdd turmeric powder, chili powder, pepper, and salt and mix well.\r\n\r\nAdd the soaked rice and gently mix with the vegetables and spices.\r\n\r\nAdd the required amount of water and cook until the rice becomes tender and fluffy.\r\n\r\nAdd the fried paneer cubes and soy sauce and gently mix everything together.\r\n\r\nCook for a few more minutes until the flavours combine well.\r\n\r\nServe hot with your favourite Sri Lankan side dishes.', '20 min', '30 min', '50 min', '4 Servings', NULL),
(14, 'prawnsmasalarice', 'Prawn Masala Rice', 'Sri Lankan Prawn Masala is a spicy and flavourful seafood dish prepared with fresh prawns, onions, garlic, ginger, tomatoes, and aromatic Sri Lankan spices. The prawns are cooked in a rich and spicy masala sauce, making this dish a delicious accompaniment to rice, roti, or other traditional meals.', 'Images/Recipes/Prawns_Masala_Rice.jpg', 'Basmati rice,\r\nPrawns,\r\nOnion,\r\nTomato,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCarrot,\r\nGreen peas,\r\nCapsicum,\r\nChili powder,\r\nTurmeric powder,\r\nCurry powder,\r\nBlack pepper,\r\nCinnamon,\r\nCardamom,\r\nCloves,\r\nCoconut milk,\r\nSalt,\r\nCooking oil', 'Wash and clean the prawns properly and remove the shells if necessary.\r\n\r\nMarinate the prawns with turmeric powder, chili powder, pepper, and salt.\r\n\r\nWash and soak the basmati rice for about 20 minutes.\r\n\r\nHeat oil in a large pan and lightly fry the marinated prawns until cooked, then set them aside.\r\n\r\nIn the same pan, sauté onion, garlic, ginger, and green chilies until fragrant.\r\n\r\nAdd chopped tomato, carrot, green peas, and capsicum and cook for a few minutes.\r\n\r\nAdd curry powder, chili powder, turmeric powder, cinnamon, cardamom, cloves, and salt and mix well.\r\n\r\nAdd the soaked rice and gently mix it with the vegetables and spices.\r\n\r\nPour in coconut milk and the required amount of water and cook until the rice becomes tender and fluffy.\r\n\r\nAdd the cooked prawns and gently mix everything together.\r\n\r\nCook for a few more minutes until the flavours combine well.\r\n\r\nServe hot with your favourite Sri Lankan side dishes.', '20 min', '20 min', '40 min', '4 Servings', NULL),
(15, 'dunthelbath', 'Sri Lankan Dunthel Bath', 'Dunthel Bath is a traditional Sri Lankan yellow rice dish prepared with rice, turmeric, ghee or butter, onions, and aromatic spices. This fragrant and colourful rice is commonly served during special occasions and family gatherings with curries, sambols, and other traditional side dishes.', 'Images/Recipes/Dunthel_Bath.jpg', 'Basmati rice,\r\nPumpkin,\r\nCoconut milk,\r\nOnion,\r\nGarlic,\r\nGinger,\r\nGreen chilies,\r\nCurry leaves,\r\nPandan leaves,\r\nCinnamon,\r\nCardamom,\r\nCloves,\r\nTurmeric powder,\r\nBlack pepper,\r\nSalt,\r\nCooking oil', 'Wash and soak the rice for about 20 minutes.\r\n\r\nPeel and cut the pumpkin into medium-sized pieces.\r\n\r\nHeat oil in a large pot and sauté onion, garlic, ginger, green chilies, curry leaves, and pandan leaves until fragrant.\r\n\r\nAdd cinnamon, cardamom, cloves, turmeric powder, black pepper, and salt and mix well.\r\n\r\nAdd the pumpkin pieces and cook for a few minutes with the spices.\r\n\r\nAdd the soaked rice and gently mix with the pumpkin and spices.\r\n\r\nPour in coconut milk and the required amount of water.\r\n\r\nCook on medium heat until the rice and pumpkin become tender.\r\n\r\nReduce the heat, cover the pot, and simmer until the rice becomes soft and fluffy.\r\n\r\nGently mix the rice and pumpkin without breaking the pumpkin pieces.\r\n\r\nServe hot with traditional Sri Lankan curries, sambols, or other side dishes.', '15 min', '30 min', '45 min', '4 Servings', NULL),
(16, 'tunafishcurry', 'Spicy Tuna Fish Curry', 'Spicy Tuna Fish Curry is a traditional Sri Lankan fish curry with a spicy and sour flavour. This curry is prepared with tuna fish, goraka, spices, and aromatic ingredients. It is commonly served with rice, bread, roti, and other Sri Lankan meals.', 'Images/Recipes/Tuna_Fish_Curry.avif', 'Tuna fish pieces,\r\nOnion,\r\nTomato,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCurry leaves,\r\nPandan leaves,\r\nTurmeric powder,\r\nChili powder,\r\nRoasted curry powder,\r\nBlack pepper,\r\nCinnamon,\r\nGoraka,\r\nCoconut milk,\r\nSalt,\r\nCooking oil', 'Wash and clean the tuna fish pieces properly.\r\n\r\nMarinate the fish with turmeric powder, chili powder, black pepper, and salt.\r\n\r\nHeat oil in a pan and sauté onion, garlic, ginger, green chilies, curry leaves, and pandan leaves until fragrant.\r\n\r\nAdd tomato and cook until it becomes soft.\r\n\r\nAdd chili powder, roasted curry powder, black pepper, cinnamon, goraka, and salt and mix well.\r\n\r\nAdd the marinated tuna pieces and gently coat them with the spices.\r\n\r\nPour in coconut milk and a small amount of water.\r\n\r\nCover the pan and cook on medium heat until the tuna becomes tender and fully cooked.\r\n\r\nSimmer for a few more minutes until the curry thickens and the flavours combine well.\r\n\r\nServe hot with steamed rice, roti, string hoppers, or other traditional Sri Lankan side dishes.', '10 mins', '15 mins', '55 mins', '3 Servings', NULL),
(17, 'sailfishcurry', 'Sri Lankan Sailfish Curry', 'Sri Lankan Sailfish Curry is a traditional spicy fish curry prepared with fresh sailfish pieces, aromatic spices, and a rich coconut-based gravy. This flavourful curry is commonly enjoyed with steamed rice and other Sri Lankan side dishes.', 'Images/Recipes/Sailfish_Curry.jpg', 'Sailfish pieces,\r\nOnion,\r\nTomato,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCurry leaves,\r\nPandan leaves,\r\nTurmeric powder,\r\nChili powder,\r\nRoasted curry powder,\r\nBlack pepper,\r\nCinnamon,\r\nGoraka,\r\nCoconut milk,\r\nSalt,\r\nCooking oil', 'Wash and clean the sailfish pieces properly.\r\n\r\nMarinate the fish with turmeric powder, chili powder, black pepper, and salt.\r\n\r\nHeat oil in a pan and sauté onion, garlic, ginger, green chilies, curry leaves, and pandan leaves until fragrant.\r\n\r\nAdd chopped tomato and cook until it becomes soft.\r\n\r\nAdd chili powder, roasted curry powder, black pepper, cinnamon, goraka, and salt and mix well.\r\n\r\nAdd the marinated sailfish pieces and gently coat them with the spices.\r\n\r\nPour in coconut milk and a small amount of water.\r\n\r\nCover the pan and cook on medium heat until the fish becomes tender and fully cooked.\r\n\r\nSimmer for a few more minutes until the curry thickens and the flavours combine well.\r\n\r\nServe hot with steamed rice, roti, string hoppers, or other traditional Sri Lankan side dishes.', '15 min', '30 min', '45 min', '4 Servings', NULL),
(18, 'chickencurry', 'Sri Lankan Chicken Curry', 'Sri Lankan Chicken Curry is a traditional spicy curry prepared with tender chicken pieces, aromatic spices, and a rich coconut-based gravy. This popular dish is loved for its deep flavour and is commonly served with steamed rice, roti, string hoppers, or other Sri Lankan meals.', 'Images/Recipes/Chicken_Curry.jpg', 'Chicken pieces,\r\nChili powder,\r\nRoasted curry powder,\r\nTurmeric powder,\r\nBlack pepper,\r\nOnion,\r\nTomato,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCurry leaves,\r\nPandan leaves,\r\nCinnamon,\r\nCardamom,\r\nCloves,\r\nCoconut milk,\r\nSalt,\r\nCooking oil', 'Clean and cut the chicken into medium-sized pieces.\r\n\r\nMarinate the chicken with chili powder, roasted curry powder, turmeric powder, black pepper, and salt.\r\n\r\nHeat oil in a large pan and sauté onion, garlic, ginger, green chilies, curry leaves, and pandan leaves until fragrant.\r\n\r\nAdd chopped tomato and cook until it becomes soft.\r\n\r\nAdd roasted curry powder, chili powder, turmeric powder, black pepper, cinnamon, cardamom, cloves, and salt and mix well.\r\n\r\nAdd the marinated chicken pieces and stir well to coat them with the spices.\r\n\r\nCook for a few minutes until the chicken absorbs the spices and develops a rich colour.\r\n\r\nAdd coconut milk and a small amount of water.\r\n\r\nCover the pan and cook slowly until the chicken becomes tender and fully cooked.\r\n\r\nSimmer for a few more minutes until the curry thickens and the flavours combine well.\r\n\r\nServe hot with steamed rice, roti, string hoppers, or other traditional Sri Lankan side dishes.', '20 min', '40 min', '1 hour', '4 Servings', NULL),
(19, 'beefcurry', 'Sri Lankan Beef Curry', 'Sri Lankan Beef Curry is a traditional spicy meat curry prepared with tender beef pieces, roasted curry spices, and aromatic ingredients. The slow cooking process allows the spices to absorb deeply into the meat, creating a rich and flavorful curry that is commonly enjoyed with rice, roti, bread, or string hoppers.', 'Images/Recipes/Beef_Curry.jpg', 'Beef pieces,\r\nChili powder,\r\nRoasted curry powder,\r\nTurmeric powder,\r\nBlack pepper,\r\nCurry powder,\r\nOnion,\r\nTomato,\r\nGreen chilies,\r\nGarlic,\r\nGinger,\r\nCurry leaves,\r\nPandan leaves,\r\nCinnamon,\r\nCardamom,\r\nCloves,\r\nCoconut milk,\r\nSalt,\r\nCooking oil', 'Clean and cut the beef into medium-sized pieces.\r\n\r\nMarinate the beef with chili powder, roasted curry powder, turmeric powder, black pepper, curry powder, and salt.\r\n\r\nHeat oil in a large pan and sauté onion, garlic, ginger, green chilies, curry leaves, and pandan leaves until fragrant.\r\n\r\nAdd chopped tomato and cook until it becomes soft.\r\n\r\nAdd roasted curry powder, chili powder, turmeric powder, black pepper, cinnamon, cardamom, cloves, and salt and mix well.\r\n\r\nAdd the marinated beef pieces and stir well to coat them with the spices.\r\n\r\nCook for a few minutes until the beef absorbs the spices.\r\n\r\nAdd coconut milk and a small amount of water.\r\n\r\nCover the pan and cook slowly until the beef becomes tender and fully cooked.\r\n\r\nSimmer for a few more minutes until the curry thickens and the flavours combine well.\r\n\r\nServe hot with steamed rice, roti, bread, or string hoppers.', '20 min', '1 hour', '1 hour 20 min', '4 Servings', NULL),
(21, 'fish2', 'Fish Ambul Thiyal', 'Sri Lankan Fish Ambul Thiyal is a traditional dry fish curry made with firm fish, goraka, black pepper, chili, and aromatic spices. The fish is slowly cooked until the gravy reduces and the pieces become dark, dry, spicy, and sour. It is commonly served with rice and other traditional Sri Lankan dishes.', 'Images/Recipes/Fish_Ambul_Thiyal.jpg', '[\"Firm fish pieces\",\"Goraka\",\"Black pepper\",\"Chili powder\",\"Turmeric powder\",\"Roasted curry powder\",\"Garlic\",\"Ginger\",\"Curry leaves\",\"Salt\"]', '[\"Clean and cut the fish into medium-sized pieces.\",\"Soak goraka in warm water and prepare a thick goraka paste.\",\"Mix the fish with goraka paste, black pepper, chili powder, turmeric, curry powder, garlic, ginger, curry leaves, and salt.\",\"Place the marinated fish in a cooking pot and add a small amount of water.\",\"Cook on medium heat until the fish becomes tender.\",\"Reduce the heat and continue cooking until the liquid completely reduces and the fish becomes dry.\",\"Turn the fish pieces carefully while cooking so they absorb the spices evenly.\",\"Serve with steamed rice and traditional Sri Lankan side dishes.\"]', '20 min', '45 min', '1 hour 5 min', '4 Servings', NULL),
(24, 'buttercake', 'Sri Lankan Butter Cake', 'Sri Lankan Butter Cake is a soft, rich, and delicious traditional cake made with butter, sugar, eggs, flour, and vanilla. It has a light and moist texture with a rich buttery flavour, making it a popular cake for tea time, birthdays, celebrations, and family gatherings.', 'Images/Recipes/Butter_Cake.jpg', 'Butter,\r\nSugar,\r\nEggs,\r\nAll-purpose flour,\r\nBaking powder,\r\nVanilla essence,\r\nFull cream milk,\r\nSalt', 'Preheat the oven to 180°C.\r\n\r\nBeat butter and sugar together until the mixture becomes light and creamy.\r\n\r\nAdd eggs one at a time and beat well after each addition.\r\n\r\nAdd vanilla essence and mix well.\r\n\r\nSift flour, baking powder, and salt together.\r\n\r\nGradually add the dry ingredients to the butter mixture while alternating with milk.\r\n\r\nMix gently until a smooth cake batter is formed.\r\n\r\nPour the batter into a greased and lined cake tin.\r\n\r\nBake at 180°C for about 35-40 minutes until golden brown and fully cooked.\r\n\r\nAllow the cake to cool before removing it from the tin.\r\n\r\nCut into slices and serve with tea or as a dessert.', '20 min', '40 min', '1 hour', '10 Servings', NULL),
(25, 'chocolatecake', 'Sri Lankan Chocolate Cake', 'Sri Lankan Chocolate Cake is a rich, soft, and delicious homemade cake made with cocoa powder, flour, butter, sugar, eggs, and milk. The moist chocolate texture and rich cocoa flavour make it a favourite dessert for birthdays, tea time, celebrations, and family gatherings.', 'Images/Recipes/Chocolate_Cake.jpg', 'All-purpose flour,\r\nCocoa powder,\r\nSugar,\r\nButter,\r\nEggs,\r\nMilk,\r\nBaking powder,\r\nVanilla essence,\r\nSalt', 'Preheat the oven to 180°C.\r\n\r\nCream the butter and sugar together until light and fluffy.\r\n\r\nAdd the eggs one at a time and beat well after each addition.\r\n\r\nAdd vanilla essence and mix well.\r\n\r\nSift the flour, cocoa powder, baking powder, and salt together.\r\n\r\nGradually add the dry ingredients to the butter mixture while alternating with milk.\r\n\r\nMix gently until a smooth chocolate cake batter is formed.\r\n\r\nPour the batter into a greased and lined cake tin.\r\n\r\nBake at 180°C for about 35-40 minutes until the cake is fully cooked.\r\n\r\nAllow the cake to cool before removing it from the tin.\r\n\r\nCut into slices and serve with tea or as a dessert.', '20 min', '40 min', '1 hour', '10 Servings', NULL),
(26, 'ribboncake', 'Sri Lankan Ribbon Cake', 'Sri Lankan Ribbon Cake is a colourful and delicious layered cake made with soft vanilla cake, butter, sugar, eggs, and different food colours. The beautiful coloured layers make it a popular choice for birthdays, celebrations, weddings, and special family occasions.', 'Images/Recipes/Ribbon_Cake.jpg', 'All-purpose flour,\r\nSugar,\r\nButter,\r\nEggs,\r\nMilk,\r\nBaking powder,\r\nVanilla essence,\r\nFood colouring,\r\nSalt', 'Preheat the oven to 180°C.\r\n\r\nCream the butter and sugar together until light and fluffy.\r\n\r\nAdd the eggs one at a time and beat well after each addition.\r\n\r\nAdd vanilla essence and mix well.\r\n\r\nSift the flour, baking powder, and salt together.\r\n\r\nGradually add the dry ingredients to the butter mixture while alternating with milk.\r\n\r\nMix gently until a smooth cake batter is formed.\r\n\r\nDivide the batter into several equal portions.\r\n\r\nAdd different food colours to the portions and mix gently.\r\n\r\nPour each coloured batter into separate greased and lined cake tins.\r\n\r\nBake at 180°C until the cake layers are fully cooked.\r\n\r\nAllow the cake layers to cool completely.\r\n\r\nPlace the coloured cake layers one on top of another with a thin layer of buttercream or icing between each layer.\r\n\r\nDecorate the top of the cake as desired.\r\n\r\nCut into slices to reveal the colourful layers and serve.', '30 min', '40 min', '1 hour 10 min', '10 Servings', NULL),
(27, 'coconutcake', 'Sri Lankan Coconut Cake', 'Sri Lankan Coconut Cake is a soft and delicious traditional cake made with grated coconut, flour, butter, sugar, eggs, and milk. The rich coconut flavour and moist texture make it a popular homemade treat enjoyed with tea, during celebrations, and at family gatherings.', 'Images/Recipes/Coconut_Cake.jpg', 'All-purpose flour,\r\nGrated coconut,\r\nSugar,\r\nButter,\r\nEggs,\r\nMilk,\r\nBaking powder,\r\nVanilla essence,\r\nSalt', 'Preheat the oven to 180°C.\r\n\r\nCream the butter and sugar together until light and fluffy.\r\n\r\nAdd the eggs one at a time and beat well after each addition.\r\n\r\nAdd vanilla essence and mix well.\r\n\r\nSift the flour, baking powder, and salt together.\r\n\r\nGradually add the dry ingredients to the butter mixture while alternating with milk.\r\n\r\nAdd the grated coconut and gently mix until evenly combined.\r\n\r\nPour the batter into a greased and lined cake tin.\r\n\r\nBake at 180°C for about 35-40 minutes until the cake is golden brown and fully cooked.\r\n\r\nAllow the cake to cool before removing it from the tin.\r\n\r\nCut into slices and serve with tea or as a dessert.', '20 min', '40 min', '1 hour', '10 Servings', NULL),
(28, 'coffeecake', 'Sri Lankan Coffee Cake', 'Sri Lankan Coffee Cake is a soft, rich, and aromatic homemade cake made with coffee, flour, butter, sugar, eggs, and milk. Its gentle coffee flavour and moist texture make it a delicious treat for tea time, celebrations, and family gatherings.', 'Images/Recipes/Coffee_Cake.jpg', 'All-purpose flour,\r\nInstant coffee,\r\nSugar,\r\nButter,\r\nEggs,\r\nMilk,\r\nBaking powder,\r\nVanilla essence,\r\nSalt', 'Preheat the oven to 180°C.\r\n\r\nDissolve the instant coffee in a small amount of warm milk and set aside.\r\n\r\nCream the butter and sugar together until light and fluffy.\r\n\r\nAdd the eggs one at a time and beat well after each addition.\r\n\r\nAdd vanilla essence and the prepared coffee mixture and mix well.\r\n\r\nSift the flour, baking powder, and salt together.\r\n\r\nGradually add the dry ingredients to the butter mixture while alternating with the remaining milk.\r\n\r\nMix gently until a smooth coffee-flavoured cake batter is formed.\r\n\r\nPour the batter into a greased and lined cake tin.\r\n\r\nBake at 180°C for about 35-40 minutes until the cake is fully cooked.\r\n\r\nAllow the cake to cool before removing it from the tin.\r\n\r\nCut into slices and serve with tea or coffee as a dessert.', '20 min', '40 min', '1 hour', '10 Servings', NULL),
(29, 'woodapplejuice', 'Sri Lankan Woodapple Juice', 'Sri Lankan Woodapple Juice is a refreshing traditional drink made from ripe woodapple pulp, water, sugar, and coconut milk. It has a rich fruity flavour with a sweet and slightly tangy taste, making it a popular Sri Lankan beverage enjoyed especially on hot days.', 'Images/Recipes/Wood_Apple_Juice.jpg', 'Ripe woodapple,\r\nWater,\r\nSugar,\r\nCoconut milk,\r\nIce cubes', 'Break the woodapple shell and scoop the ripe pulp into a bowl.\r\n\r\nRemove any hard seeds or unwanted pieces from the pulp.\r\n\r\nAdd the woodapple pulp to a blender.\r\n\r\nAdd water and blend until the pulp becomes smooth.\r\n\r\nAdd sugar according to taste and blend again.\r\n\r\nAdd coconut milk and mix well until the juice becomes creamy.\r\n\r\nStrain the juice if a smoother texture is preferred.\r\n\r\nAdd ice cubes and chill before serving.\r\n\r\nServe cold as a refreshing traditional Sri Lankan drink.', '10 min', '10 min', '20 min', '4 Servings', NULL),
(30, 'mangojuice', 'Sri Lankan Mango Juice', 'Sri Lankan Mango Juice is a refreshing and naturally sweet drink made with ripe Sri Lankan mangoes, water, sugar, and a little lime juice. It has a smooth tropical flavour and a delicious tropical taste, making it a popular homemade beverage enjoyed especially on hot days and during family gatherings.', 'Images/Recipes/Mango_Juice.jpg', 'Ripe mangoes,\r\nWater,\r\nSugar,\r\nLime juice,\r\nIce cubes', 'Wash and peel the ripe mangoes.\r\n\r\nCut the mangoes into small pieces and remove the seeds.\r\n\r\nAdd the mango pieces to a blender.\r\n\r\nAdd water and blend until smooth.\r\n\r\nAdd sugar and lime juice according to taste and blend again.\r\n\r\nAdd more water if a lighter consistency is preferred.\r\n\r\nStrain the juice if a smoother texture is desired.\r\n\r\nAdd ice cubes and chill before serving.\r\n\r\nServe cold as a refreshing Sri Lankan fruit drink.', '10 min', '5 min', '15 min', '4 Servings', NULL),
(31, 'watermelonjuice', 'Sri Lankan Watermelon Juice', 'Sri Lankan Watermelon Juice is a refreshing and naturally sweet drink made with fresh watermelon, water, lime juice, and ice. Its juicy and cooling flavour makes it a popular homemade beverage, especially on hot days and during family gatherings.', 'Images/Recipes/Watermelon_Juice.jpg', 'Fresh watermelon,\r\nWater,\r\nSugar,\r\nLime juice,\r\nIce cubes', 'Wash the watermelon and cut it into small pieces.\r\n\r\nRemove the seeds from the watermelon pieces.\r\n\r\nAdd the watermelon pieces to a blender.\r\n\r\nBlend until the watermelon becomes smooth and juicy.\r\n\r\nAdd water, sugar, and lime juice according to taste.\r\n\r\nBlend again until all the ingredients are well combined.\r\n\r\nStrain the juice if a smoother texture is preferred.\r\n\r\nAdd ice cubes and chill before serving.\r\n\r\nServe cold as a refreshing Sri Lankan fruit drink.', '10 min', '5 min', '15 min', '4 Servings', NULL),
(32, 'orangejuice', 'Sri Lankan Orange Juice', 'Sri Lankan Orange Juice is a refreshing and naturally sweet fruit drink made with fresh oranges, water, sugar, and ice. Its fresh citrus flavour makes it a popular homemade beverage enjoyed on hot days, during family gatherings, and with meals.', 'Images/Recipes/Orange_Juice.jpg', 'Fresh oranges,\r\nWater,\r\nSugar,\r\nIce cubes', 'Wash the oranges thoroughly.\r\n\r\nCut the oranges in half and squeeze out the fresh juice.\r\n\r\nRemove any seeds from the juice.\r\n\r\nAdd water and sugar according to taste and mix well.\r\n\r\nStir until the sugar is completely dissolved.\r\n\r\nAdd ice cubes and chill before serving.\r\n\r\nServe cold as a refreshing fresh fruit drink.', '10 min', '5 min', '15 min', '4 Servings', NULL),
(33, 'avocadojuice', 'Sri Lankan Avocado Juice', 'Sri Lankan Avocado Juice is a creamy and refreshing traditional-style drink made with ripe avocado, milk, sugar, and ice. Its smooth texture and rich flavour make it a popular homemade beverage enjoyed as a refreshing drink or light dessert.', 'Images/Recipes/Avocado_Juice.jpg', 'Ripe avocado,\r\nFull cream milk,\r\nSugar,\r\nWater,\r\nIce cubes', 'Wash and cut the ripe avocado into two halves.\r\n\r\nRemove the seed and scoop the avocado flesh into a blender.\r\n\r\nAdd full cream milk, water, and sugar according to taste.\r\n\r\nBlend until the mixture becomes smooth and creamy.\r\n\r\nAdd more milk or water if a lighter consistency is preferred.\r\n\r\nAdd ice cubes and blend briefly until well combined.\r\n\r\nChill the juice before serving.\r\n\r\nServe cold as a creamy and refreshing Sri Lankan-style fruit drink.', '10 min', '5 min', '15 min', '4 Servings', NULL),
(34, 'milkrice', 'Sri Lankan Milk Rice', 'Sri Lankan Milk Rice, also known as Kiribath, is a traditional Sri Lankan dish made by cooking rice with coconut milk until it becomes soft, creamy, and firm. It is commonly prepared for breakfast, special occasions, celebrations, and traditional Sri Lankan gatherings.', 'Images/Recipes/Milk_Rice.jpg', 'White rice,\r\nCoconut milk,\r\nWater,\r\nSalt', 'Wash the rice thoroughly and drain the water.\r\n\r\nAdd the rice and water to a rice cooker or large pot.\r\n\r\nCook the rice until it becomes soft and fully cooked.\r\n\r\nAdd coconut milk and salt to the cooked rice.\r\n\r\nMix gently and continue cooking until the rice becomes creamy and thick.\r\n\r\nTransfer the milk rice onto a flat tray or plate.\r\n\r\nSpread the mixture evenly and flatten the surface using a spoon or spatula.\r\n\r\nAllow the milk rice to cool and set.\r\n\r\nCut the milk rice into traditional diamond or square pieces.\r\n\r\nServe with lunu miris, coconut sambol, or a spicy curry.', '15 min', '30 min', '45 min', '6 Servings', NULL),
(35, 'athirasa', 'Sri Lankan Athirasa', 'Sri Lankan Athirasa is a traditional sweet made with rice flour, kithul treacle, sugar, and aromatic spices. It has a soft and slightly chewy texture with a rich sweet flavour and is especially popular during the Sinhala and Tamil New Year and other special occasions.', 'Images/Recipes/Athirasa.jpg', 'Rice flour,\r\nKithul treacle,\r\nSugar,\r\nCardamom,\r\nFennel seeds,\r\nSalt,\r\nWater,\r\nCoconut oil', 'Heat the kithul treacle and sugar together in a pan until the sugar dissolves and the mixture becomes slightly thick.\r\n\r\nAdd crushed cardamom, fennel seeds, and a small amount of salt.\r\n\r\nGradually add the rice flour to the treacle mixture while stirring continuously.\r\n\r\nMix well until a soft and slightly sticky dough is formed.\r\n\r\nAllow the dough to cool enough to handle.\r\n\r\nDivide the dough into small portions and shape each portion into a flat round shape.\r\n\r\nHeat coconut oil in a deep frying pan.\r\n\r\nDeep-fry the shaped Athirasa pieces on medium heat until they become golden brown.\r\n\r\nRemove them from the oil and drain on paper towels.\r\n\r\nAllow them to cool before serving.\r\n\r\nServe as a traditional Sri Lankan sweet during celebrations and special occasions.', '30 min', '20 min', '50 min', '10 Servings', NULL),
(36, 'kokis', 'Sri Lankan Kokis', 'Sri Lankan Kokis is a traditional crispy and crunchy Sri Lankan snack made with rice flour, coconut milk, eggs, and spices. It is especially popular during the Sinhala and Tamil New Year and is enjoyed as a festive snack with its golden colour and delicate crispy texture.', 'Images/Recipes/Kokis.jpg', 'Rice flour,\r\nCoconut milk,\r\nEggs,\r\nTurmeric powder,\r\nSalt,\r\nWater,\r\nCoconut oil', 'Add rice flour, turmeric powder, and salt to a mixing bowl.\r\n\r\nAdd the eggs and mix well.\r\n\r\nGradually add coconut milk and water while mixing until a smooth batter is formed.\r\n\r\nHeat coconut oil in a deep frying pan.\r\n\r\nDip the kokis mould into the hot oil for a few seconds to heat it.\r\n\r\nDip the heated mould into the batter without completely covering the top of the mould.\r\n\r\nPlace the mould back into the hot oil and fry until the kokis becomes golden and crispy.\r\n\r\nGently remove the kokis from the mould.\r\n\r\nRepeat the process with the remaining batter.\r\n\r\nDrain the kokis on paper towels to remove excess oil.\r\n\r\nAllow them to cool and serve as a traditional Sri Lankan festive snack.', '20 min', '30 min', '50 min', '10 Servings', NULL),
(37, 'aluwa', 'Sri Lankan Aluwa', 'Sri Lankan Aluwa is a traditional Sri Lankan sweet made with roasted rice flour, sugar syrup, cashew nuts, and aromatic spices. It has a soft, slightly firm texture and is commonly prepared during the Sinhala and Tamil New Year and other special celebrations.', 'Images/Recipes/Aluwa.jpg', 'Rice flour,\r\nSugar,\r\nCashew nuts,\r\nCardamom,\r\nFennel seeds,\r\nSalt,\r\nWater', 'Roast the rice flour lightly in a dry pan until it becomes fragrant and set it aside.\r\n\r\nHeat sugar and water in a pan and cook until a thick sugar syrup is formed.\r\n\r\nAdd crushed cardamom, fennel seeds, cashew nuts, and a small amount of salt to the syrup.\r\n\r\nGradually add the roasted rice flour while stirring continuously.\r\n\r\nMix well until a thick and smooth mixture is formed.\r\n\r\nSpread the mixture onto a greased flat tray.\r\n\r\nFlatten the mixture evenly using a spoon or rolling pin.\r\n\r\nAllow it to cool and set completely.\r\n\r\nCut the Aluwa into diamond or square-shaped pieces.\r\n\r\nServe as a traditional Sri Lankan sweet during celebrations and special occasions.', '20 min', '20 min', '40 min', '10 Servings', NULL),
(38, 'mungkawum', 'Sri Lankan Mung Kawum', 'Sri Lankan Mung Kawum is a traditional Sri Lankan sweet made with roasted mung beans, rice flour, kithul treacle, and coconut. It is commonly prepared during the Sinhala and Tamil New Year and other special celebrations.', 'Images/Recipes/Mung_Kawum.jpg', 'Mung beans,\r\nRice flour,\r\nKithul treacle,\r\nGrated coconut,\r\nCardamom,\r\nSalt,\r\nWater,\r\nCoconut oil', 'Roast the mung beans in a dry pan until they become golden and fragrant.\r\n\r\nAllow the roasted mung beans to cool and grind them into a fine powder.\r\n\r\nMix the mung bean powder with rice flour, grated coconut, cardamom, and a small amount of salt.\r\n\r\nGradually add kithul treacle and mix well to form a soft and firm dough.\r\n\r\nDivide the mixture into small portions and shape them into small flat round pieces.\r\n\r\nHeat coconut oil in a deep frying pan.\r\n\r\nDeep-fry the shaped Mung Kawum on medium heat until they become golden brown.\r\n\r\nRemove them from the oil and drain on paper towels.\r\n\r\nAllow them to cool before serving.\r\n\r\nServe as a traditional Sri Lankan sweet during celebrations and special occasions.', '30 min', '20 min', '50 min', '10 Servings', NULL),
(39, 'sweetpongal', 'Sweet Pongal (Sakkarai Pongal)', 'Sweet Pongal, also known as Sakkarai Pongal, is a traditional South Indian sweet rice dish made with rice, moong dal, jaggery, coconut milk, and aromatic spices. It is commonly prepared during festivals and special occasions and is enjoyed for its rich, sweet, and creamy flavour.', 'Images/Recipes/Sweet_Pongal.jpg', 'Rice,\r\nMoong dal,\r\nJaggery,\r\nCoconut milk,\r\nCashew nuts,\r\nRaisins,\r\nCardamom,\r\nGhee,\r\nSalt', 'Wash the rice and moong dal thoroughly.\r\n\r\nDry roast the moong dal lightly until fragrant.\r\n\r\nAdd the rice and roasted moong dal to a pot with water and cook until soft and creamy.\r\n\r\nMelt the jaggery with a small amount of water and strain it to remove impurities.\r\n\r\nAdd the jaggery syrup to the cooked rice and dal mixture.\r\n\r\nAdd coconut milk, cardamom, and a small amount of salt and mix well.\r\n\r\nCook on low heat until the mixture becomes thick and creamy.\r\n\r\nHeat ghee in a small pan and fry the cashew nuts and raisins until golden.\r\n\r\nAdd the fried cashew nuts and raisins to the Pongal and mix well.\r\n\r\nServe warm as a traditional sweet dish during festivals and special occasions.', '15 min', '30 min', '45 min', '6 Servings', NULL),
(40, 'savorypongal', 'Savory Pongal (Ven Pongal)', 'Savory Pongal, also known as Ven Pongal, is a traditional South Indian rice and lentil dish made with rice, moong dal, ghee, black pepper, cumin, ginger, and curry leaves. It has a soft and creamy texture with a delicious savoury flavour and is commonly enjoyed as a breakfast or festive dish.', 'Images/Recipes/Savory_Pongal.webp', 'Rice,\r\nMoong dal,\r\nGhee,\r\nBlack pepper,\r\nCumin seeds,\r\nGinger,\r\nCurry leaves,\r\nCashew nuts,\r\nSalt,\r\nWater', 'Wash the rice and moong dal thoroughly.\r\n\r\nDry roast the moong dal lightly until fragrant.\r\n\r\nAdd the rice and roasted moong dal to a pot with water.\r\n\r\nCook until the rice and dal become very soft and creamy.\r\n\r\nHeat ghee in a small pan.\r\n\r\nAdd cumin seeds, black pepper, chopped ginger, curry leaves, and cashew nuts.\r\n\r\nFry until the cashew nuts become golden and the spices become fragrant.\r\n\r\nAdd the fried tempering to the cooked rice and dal mixture.\r\n\r\nAdd salt and mix everything well.\r\n\r\nCook on low heat for a few more minutes until the flavours combine.\r\n\r\nServe hot as a traditional savory Pongal with coconut chutney or sambar.', '10 min', '30 min', '40 min', '4 Servings', NULL),
(41, 'vegetablestew', 'Vegetable Stew (Pongal Kootu)', 'Vegetable Stew, also known as Pongal Kootu, is a traditional South Indian vegetable dish made with mixed vegetables, lentils, coconut, and aromatic spices. It has a mild, creamy, and savoury flavour and is commonly served with rice or Pongal during traditional meals and festivals.', 'Images/Recipes/Vegetable_Stew.jpg', 'Mixed vegetables,\r\nMoong dal,\r\nGrated coconut,\r\nGreen chilies,\r\nCumin seeds,\r\nTurmeric powder,\r\nCurry leaves,\r\nMustard seeds,\r\nDried red chilies,\r\nSalt,\r\nWater,\r\nCooking oil', 'Wash and cut the vegetables into small, even-sized pieces.\r\n\r\nWash the moong dal thoroughly.\r\n\r\nCook the moong dal with water and turmeric powder until it becomes soft.\r\n\r\nAdd the chopped vegetables and cook until they become tender.\r\n\r\nGrind grated coconut, green chilies, and cumin seeds with a little water to make a smooth paste.\r\n\r\nAdd the coconut paste to the cooked vegetables and dal.\r\n\r\nAdd salt and mix well.\r\n\r\nCook on low heat for a few minutes until the flavours combine and the mixture becomes slightly thick.\r\n\r\nHeat oil in a small pan and add mustard seeds.\r\n\r\nAdd dried red chilies and curry leaves and fry until fragrant.\r\n\r\nPour the tempering over the vegetable stew and mix gently.\r\n\r\nServe hot with steamed rice, Pongal, or other traditional South Indian dishes.', '20 min', '30 min', '50 min', '4 Servings', NULL);
INSERT INTO `recipes` (`id`, `recipe_key`, `title`, `description`, `image`, `ingredients`, `instructions`, `prep_time`, `cook_time`, `total_time`, `servings`, `user_id`) VALUES
(42, 'meduvada', 'Medu Vada (Crispy Lentil Fritters)', 'Medu Vada is a popular South Indian crispy lentil fritter made with urad dal, green chilies, ginger, curry leaves, and aromatic spices. It has a crispy golden exterior with a soft and fluffy inside and is commonly served with coconut chutney and sambar.', 'Images/Recipes/Medu_Vada.jpg', 'Urad dal,\r\nGreen chilies,\r\nGinger,\r\nCurry leaves,\r\nBlack pepper,\r\nCumin seeds,\r\nSalt,\r\nWater,\r\nCooking oil', 'Wash the urad dal thoroughly and soak it in water for several hours.\r\n\r\nDrain the soaked dal completely.\r\n\r\nGrind the dal with a small amount of water until a smooth and fluffy batter is formed.\r\n\r\nAdd chopped green chilies, ginger, curry leaves, black pepper, cumin seeds, and salt.\r\n\r\nMix the batter well until all the ingredients are evenly combined.\r\n\r\nHeat cooking oil in a deep frying pan.\r\n\r\nWet your hands and take a small portion of batter.\r\n\r\nShape the batter into a round fritter with a small hole in the centre.\r\n\r\nCarefully place the vada into the hot oil.\r\n\r\nDeep-fry until the vada becomes golden brown and crispy on the outside.\r\n\r\nRemove from the oil and drain on paper towels.\r\n\r\nRepeat with the remaining batter.\r\n\r\nServe hot with coconut chutney and sambar.', '4 hours', '30 min', '4 hours 30 min', '10 Servings', NULL),
(43, 'paalpayasam', 'Paal Payasam (Festive Rice Kheer)', 'Paal Payasam is a traditional South Indian rice pudding made with rice, milk, sugar, cardamom, and nuts. It is creamy, rich, and mildly sweet, making it a popular dessert served during festivals, religious ceremonies, and special family occasions.', 'Images/Recipes/Paal_Payasam.jpg', 'Rice,\r\nFull cream milk,\r\nSugar,\r\nCardamom,\r\nCashew nuts,\r\nRaisins,\r\nGhee', 'Wash the rice thoroughly and drain the water.\r\n\r\nAdd the rice and milk to a heavy-bottomed pot.\r\n\r\nCook on low heat, stirring occasionally, until the rice becomes soft and the milk thickens.\r\n\r\nAdd sugar and mix well until it completely dissolves.\r\n\r\nAdd crushed cardamom and continue cooking for a few more minutes.\r\n\r\nHeat ghee in a small pan and fry the cashew nuts and raisins until golden.\r\n\r\nAdd the fried cashew nuts and raisins to the payasam.\r\n\r\nMix well and simmer for a few minutes until the flavours combine.\r\n\r\nServe warm or chilled as a traditional festive dessert.', '10 min', '45 min', '55 min', '6 Servings', NULL),
(44, 'gulabjamun', 'Gulab Jamun', 'Gulab Jamun is a popular South Asian sweet made from soft milk-based dough balls that are deep-fried until golden brown and soaked in a fragrant sugar syrup. It is a rich and delicious dessert commonly served during festivals, celebrations, and special occasions.', 'Images/Recipes/Gulab_Jamun.jpg', 'Milk powder,\r\nAll-purpose flour,\r\nBaking powder,\r\nGhee,\r\nMilk,\r\nSugar,\r\nWater,\r\nCardamom,\r\nRose water,\r\nCooking oil', 'Add milk powder, all-purpose flour, and baking powder to a mixing bowl.\r\n\r\nAdd ghee and mix well.\r\n\r\nGradually add milk and gently combine until a soft dough is formed.\r\n\r\nAllow the dough to rest for a few minutes.\r\n\r\nDivide the dough into small portions and roll them into smooth balls without cracks.\r\n\r\nHeat cooking oil in a deep frying pan.\r\n\r\nDeep-fry the dough balls on low to medium heat until they become evenly golden brown.\r\n\r\nRemove the fried balls and drain the excess oil.\r\n\r\nPrepare the sugar syrup by boiling sugar and water together.\r\n\r\nAdd crushed cardamom and rose water to the syrup.\r\n\r\nPlace the fried Gulab Jamun balls into the warm sugar syrup.\r\n\r\nAllow them to soak for several hours so they become soft and absorb the syrup.\r\n\r\nServe warm or chilled as a delicious dessert.', '20 min', '30 min', '50 min', '10 Servings', NULL),
(45, 'basbousa', 'Basbousa (Semolina Coconut Cake)', 'Basbousa is a popular Middle Eastern sweet cake made with semolina, coconut, sugar, yogurt, and butter. It has a soft and slightly crumbly texture with a rich coconut flavour and is soaked in sweet sugar syrup after baking, making it a delicious dessert for celebrations and special occasions.', 'Images/Recipes/Basbousa.jpg', 'Semolina,\r\nGrated coconut,\r\nSugar,\r\nYogurt,\r\nButter,\r\nBaking powder,\r\nVanilla essence,\r\nAlmonds,\r\nWater,\r\nLemon juice', 'Preheat the oven to 180°C.\r\n\r\nMix semolina, grated coconut, sugar, and baking powder in a large bowl.\r\n\r\nAdd melted butter, yogurt, and vanilla essence and mix until a thick batter is formed.\r\n\r\nSpread the mixture evenly in a greased baking tray.\r\n\r\nScore the surface into diamond or square shapes and place an almond on each piece.\r\n\r\nBake at 180°C until the surface becomes golden brown and the cake is fully cooked.\r\n\r\nPrepare the sugar syrup by boiling sugar and water together.\r\n\r\nAdd lemon juice to the syrup and simmer for a few minutes.\r\n\r\nPour the warm sugar syrup over the hot Basbousa immediately after removing it from the oven.\r\n\r\nAllow the Basbousa to absorb the syrup and cool completely.\r\n\r\nCut along the scored lines and serve.', '15 min', '35 min', '50 min', '10 Servings', NULL),
(46, 'vermicellifruitcustard', 'Vermicelli Fruit Custard', 'Vermicelli Fruit Custard is a creamy and refreshing dessert made with vermicelli, milk, custard powder, sugar, and fresh fruits. It combines soft vermicelli, smooth custard, and colourful fruits, making it a delicious dessert for family gatherings, celebrations, and special occasions.', 'Images/Recipes/Vermicelli_Fruit_Custard.avif', 'Vermicelli,\r\nFull cream milk,\r\nCustard powder,\r\nSugar,\r\nBanana,\r\nApple,\r\nMango,\r\nGrapes,\r\nCashew nuts', 'Break the vermicelli into small pieces.\r\n\r\nBoil water in a pan and cook the vermicelli until soft.\r\n\r\nDrain the cooked vermicelli and set it aside.\r\n\r\nHeat milk in a saucepan and add sugar.\r\n\r\nMix custard powder with a small amount of cold milk to make a smooth paste.\r\n\r\nGradually add the custard mixture to the hot milk while stirring continuously.\r\n\r\nCook on low heat until the custard becomes smooth and slightly thick.\r\n\r\nAdd the cooked vermicelli and mix well.\r\n\r\nAllow the mixture to cool completely.\r\n\r\nCut the fruits into small pieces.\r\n\r\nAdd the fruits to the cooled custard and vermicelli mixture.\r\n\r\nMix gently and refrigerate for a few hours.\r\n\r\nServe chilled as a refreshing fruit dessert.', '20 min', '25 min', '45 min', '6 Servings', NULL),
(47, 'rasmalai', 'Rasmalai', 'Rasmalai is a popular South Asian dessert made with soft paneer cheese dumplings soaked in sweet, creamy, and lightly flavoured milk. It is traditionally garnished with cardamom and nuts and served chilled during festivals, celebrations, and special occasions.', 'Images/Recipes/Rasmalai.avif', 'Full cream milk,\r\nLemon juice,\r\nSugar,\r\nCardamom,\r\nSaffron,\r\nPistachios,\r\nAlmonds,\r\nWater', 'Boil the milk and add lemon juice gradually until the milk curdles.\r\n\r\nStrain the curdled milk through a clean cloth to separate the paneer.\r\n\r\nWash the paneer with cold water and squeeze out the excess water.\r\n\r\nKnead the paneer until it becomes smooth and soft.\r\n\r\nDivide the paneer into small portions and shape them into flat round discs.\r\n\r\nBoil water and sugar in a wide pan to prepare the sugar syrup.\r\n\r\nAdd the paneer discs to the boiling syrup and cook until they become soft and slightly expanded.\r\n\r\nHeat milk in another pan and simmer until it reduces slightly.\r\n\r\nAdd sugar, cardamom, and saffron to the milk and mix well.\r\n\r\nGently add the cooked paneer discs to the sweet milk.\r\n\r\nAllow the Rasmalai to cool and refrigerate for a few hours.\r\n\r\nGarnish with chopped pistachios and almonds.\r\n\r\nServe chilled as a creamy and delicious dessert.', '30 min', '45 min', '1 hour 15 min', '8 Servings', NULL),
(48, 'christmascake', 'Joyous Christmas Cake', 'Joyous Christmas Cake is a rich and festive fruit cake made with dried fruits, cashew nuts, spices, eggs, butter, and sweeteners. It is traditionally enjoyed during Christmas celebrations and family gatherings, with its rich flavour and aromatic spices making it a special festive dessert.', 'Images/Recipes/Christmas_Cake.avif', 'All-purpose flour,\r\nButter,\r\nSugar,\r\nEggs,\r\nMixed dried fruits,\r\nCashew nuts,\r\nAlmonds,\r\nCherries,\r\nDates,\r\nRaisins,\r\nMixed spices,\r\nVanilla essence,\r\nRose essence,\r\nMilk,\r\nBaking powder', 'Soak the dried fruits and raisins in a suitable mixture for several hours or overnight.\r\n\r\nPreheat the oven to 160°C.\r\n\r\nCream the butter and sugar together until light and fluffy.\r\n\r\nAdd the eggs one at a time and beat well after each addition.\r\n\r\nAdd vanilla essence and rose essence and mix well.\r\n\r\nSift the flour, baking powder, and mixed spices together.\r\n\r\nGradually add the dry ingredients to the butter mixture and mix gently.\r\n\r\nAdd the soaked fruits, cashew nuts, almonds, cherries, and dates.\r\n\r\nFold everything together until the ingredients are evenly distributed.\r\n\r\nPour the mixture into a greased and lined cake tin.\r\n\r\nBake at 160°C for about 1 hour 30 minutes to 2 hours until the cake is fully cooked.\r\n\r\nAllow the cake to cool completely before removing it from the tin.\r\n\r\nCut into slices and serve during Christmas celebrations.', '1 hour', '2 hours', '3 hours', '12 Servings', NULL),
(49, 'christmasfudge', 'Jolly Christmas Fudge', 'Jolly Christmas Fudge is a rich and creamy festive sweet made with chocolate, condensed milk, butter, and colourful toppings. Its smooth texture and sweet chocolate flavour make it a delicious treat for Christmas celebrations, parties, and family gatherings.', 'Images/Recipes/Christmas_Fudge.avif', 'Chocolate,\r\nCondensed milk,\r\nButter,\r\nCocoa powder,\r\nVanilla essence,\r\nCashew nuts,\r\nAlmonds,\r\nChristmas sprinkles', 'Break the chocolate into small pieces and place it in a heatproof bowl.\r\n\r\nAdd condensed milk and butter to the chocolate.\r\n\r\nMelt the mixture over low heat while stirring continuously until smooth and well combined.\r\n\r\nAdd cocoa powder and vanilla essence and mix well.\r\n\r\nAdd chopped cashew nuts and almonds and stir gently.\r\n\r\nPour the mixture into a lined baking tray.\r\n\r\nSpread the mixture evenly and smooth the surface.\r\n\r\nDecorate the top with Christmas sprinkles.\r\n\r\nRefrigerate for several hours until the fudge becomes firm.\r\n\r\nRemove the fudge from the tray and cut it into small squares.\r\n\r\nServe as a festive Christmas sweet.', '15 min', '15 min', '30 min', '12 Servings', NULL),
(50, 'gingerbreadcookies', 'Merry Gingerbread Cookies', 'Merry Gingerbread Cookies are classic festive cookies made with flour, butter, brown sugar, ginger, cinnamon, and other aromatic spices. They have a delicious warm flavour and crisp edges with a soft centre, making them a popular Christmas treat for families and celebrations.', 'Images/Recipes/Gingerbread_Cookies.jpg', 'All-purpose flour,\r\nButter,\r\nBrown sugar,\r\nEgg,\r\nGinger powder,\r\nCinnamon powder,\r\nNutmeg powder,\r\nBaking soda,\r\nVanilla essence,\r\nSalt', 'Preheat the oven to 180°C.\r\n\r\nCream the butter and brown sugar together until light and smooth.\r\n\r\nAdd the egg and vanilla essence and mix well.\r\n\r\nSift the flour, ginger powder, cinnamon powder, nutmeg, baking soda, and salt together.\r\n\r\nGradually add the dry ingredients to the butter mixture and mix until a soft dough is formed.\r\n\r\nWrap the dough and refrigerate it for about 30 minutes.\r\n\r\nRoll the dough out on a lightly floured surface.\r\n\r\nCut the dough into gingerbread shapes using cookie cutters.\r\n\r\nPlace the cookies on a lined baking tray.\r\n\r\nBake at 180°C for about 10 to 12 minutes until the edges become lightly golden.\r\n\r\nAllow the cookies to cool completely before decorating or serving.\r\n\r\nServe as a festive Christmas treat.', '40 min', '12 min', '52 min', '15 Servings', NULL),
(51, 'sprinklecookies', 'Sprinkle Cookies', 'Sprinkle Cookies are colourful and delicious homemade cookies made with butter, sugar, flour, eggs, and colourful sprinkles. They have a soft and buttery texture with a sweet flavour and are perfect for parties, celebrations, Christmas, and family gatherings.', 'Images/Recipes/Sprinkle_Cookies.avif', 'All-purpose flour,\r\nButter,\r\nSugar,\r\nEgg,\r\nVanilla essence,\r\nBaking powder,\r\nSalt,\r\nColourful sprinkles', 'Preheat the oven to 180°C.\r\n\r\nCream the butter and sugar together until light and fluffy.\r\n\r\nAdd the egg and vanilla essence and mix well.\r\n\r\nSift the flour, baking powder, and salt together.\r\n\r\nGradually add the dry ingredients to the butter mixture and mix until a soft cookie dough is formed.\r\n\r\nAdd the colourful sprinkles and gently mix them into the dough.\r\n\r\nTake small portions of dough and roll them into balls.\r\n\r\nPlace the dough balls on a lined baking tray and gently flatten them.\r\n\r\nAdd extra sprinkles on top if desired.\r\n\r\nBake at 180°C for about 10 to 12 minutes until the edges become lightly golden.\r\n\r\nAllow the cookies to cool completely before serving.\r\n\r\nServe as a colourful and delicious sweet treat.', '20 min', '12 min', '32 min', '15 Servings', NULL),
(52, 'christmasjellies', 'Christmas Jellies', 'Christmas Jellies are colourful and fun festive sweets made with fruit-flavoured jelly, sugar, and gelatin. They have a soft and chewy texture with bright colours, making them a popular treat for Christmas parties, family gatherings, and celebrations.', 'Images/Recipes/Christmas_Jellies.jpg', 'Gelatin powder,\r\nFruit juice,\r\nSugar,\r\nWater,\r\nLemon juice,\r\nFood colouring,\r\nFruit essence', 'Add gelatin powder to a small amount of cold water and allow it to soften.\r\n\r\nHeat fruit juice and sugar in a saucepan over low heat.\r\n\r\nStir until the sugar completely dissolves.\r\n\r\nAdd the softened gelatin and mix until it dissolves completely.\r\n\r\nAdd lemon juice and fruit essence and mix well.\r\n\r\nDivide the mixture into separate bowls if different colours are desired.\r\n\r\nAdd a small amount of food colouring to each bowl.\r\n\r\nPour the mixtures into lightly greased moulds or a flat tray.\r\n\r\nRefrigerate for several hours until the jelly becomes firm.\r\n\r\nRemove the jellies from the moulds or cut them into small shapes.\r\n\r\nServe as a colourful and festive Christmas sweet.', '15 min', '10 min', '25 min', '15 Servings', NULL);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(225) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `username`, `email`, `password`, `created_at`) VALUES
(15, 'TestUser', 'test@gmail.com', '$2y$10$zSW15zdmEQHKSRFIj0H8n.liom5X7u7xMrhGRXY8NoFUeq.xn8cMu', '2026-08-12 15:35:07'),
(27, 'Yovi', 'Yovi12@gmail.com', '$2y$10$/YDZEPZwQO5ic5Sw7iQk4.gCp7/ixMNwDNOcSfokRCuvUs0LPH17q', '2026-08-05 16:28:02'),
(28, 'dinu', 'dinu@gmail.com', '$2y$10$O1.fQrz717I/gLRPRmu9xudL8otCAnYNxUPtuajVp/I3SBYTW.dVC', '2026-08-06 08:51:30'),
(29, 'dinu', 'dinu@gmail.com', '$2y$10$nIfooBaHT56dqTxmB6.yVua1J98JHGqosI88u5OzART8CbybVZjMS', '2026-08-06 08:53:53'),
(30, 'para', 'viha@gimail.com', '$2y$10$xmcemcQ2ZqTR.fHNPRL1duHDDOrB.DoG4g4hZCdV2/X3g2vJDFl5a', '2026-08-06 08:58:36'),
(31, 'tharu', 'taru@gmail.com', '$2y$10$9RZB0uhcFjvGM4gaBExiYOX44MyRdY.wq1LF3EI.hfBVfFCsyNSQi', '2026-08-06 09:05:24'),
(32, 'hhfhf', 'fffff@gmail.com', '$2y$10$2ac1jonAgPHHgUZQqDE7k.3asplk6s4W2LH4R/XHLQ18mSMbOVM1i', '2026-08-06 09:12:18'),
(33, 'testuser', 'test2@gmail.com', '$2y$10$UjEHBGGljVm2BdlvShPe3OzadUa1uOxvHxqul4MUX3C5Zoh9X1/mK', '2026-08-06 09:14:40'),
(34, 'newuser', 'newuser@gmail.com', '$2y$10$eLFUYneZyIM4FYLYky9Ax.LqB43XmnOhpui2Aygs51gedoo5snCXa', '2026-08-06 09:27:02'),
(35, 'yovie', 'yovindu@gmail.com', '$2y$10$F3hnQkRx5p5h2YD.LdjaiOn1CsEi89V7MleHb5dSDE.nIeyCcoZu2', '2026-08-06 09:32:34');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `messages`
--
ALTER TABLE `messages`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `recipe_key` (`recipe_key`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `messages`
--
ALTER TABLE `messages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
